### ISSUE TITLE
It's Down?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [SaraVieira/webpack.wtf#44]
When I enter [webpack.wtf](https://webpack.wtf) it only shows this:

![image](https://user-images.githubusercontent.com/11427028/41942885-3ad2dd5e-7999-11e8-9b59-f21d84d1f433.png)

**Comment by DanielRamosAcosta** [comment]
Spoiler, yes it's down.

**Comment by SaraVieira** [comment]
I don't think it actually had anything 😂

**Comment by DanielRamosAcosta** [comment]
I think that at the moment, I opened the issue in the wrong repo hahaha sorry.
